# config/meta.yml

meta_product_name: "YoN"
meta_title: "Yay or Nay - Come Yay with us !"
meta_description: "Yay ta vie, Nay tes problèmes"
meta_image: "YONcover.png"                       # should exist in `app/assets/images/`
